spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 55MB
  mail:
    host: mail.quinto.site
    port: 25
    properties:
      mail:
        smtp:
          auth: true
    username: desarrollo@quinto.site
    password: Carmelita23

  datasource:
    url: jdbc:mysql://localhost:3306/mov?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        search:
          default:
            directory_provider: filesystem
            indexBase: ./data/lucene

  thymeleaf:
    cache: false
  resources:
    cache:
      cachecontrol:
        max-age: 365d
        no-cache: false
server:
  port: 8080
  error:
    path: /error
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 28800
      cookie:
        http-only: true
      tracking-modes:
        - cookie
